#!/usr/bin/env bash
#Based on post at:
#http://www.reddit.com/r/linux/comments/qagsu/easy_colors_for_shell_scripts_color_library/

 bold=`echo -en "\033[1m"`
 underline=`echo -en "\033[4m"`
 dim=`echo -en "\033[2m"`
 strickthrough=`echo -en "\033[9m"`
 blink=`echo -en "\033[5m"`
 reverse=`echo -en "\033[7m"`
 hidden=`echo -en "\033[8m"`
 normal=`echo -en "\033[0m"`
 black=`echo -en "\033[30m"`
 red=`echo -en "\033[31m"`
 green=`echo -en "\033[32m"`
 orange=`echo -en "\033[33m"`
 blue=`echo -en "\033[34m"`
 purple=`echo -en "\033[35m"`
 aqua=`echo -en "\033[36m"`
 gray=`echo -en "\033[37m"`
 darkgray=`echo -en "\033[90m"`
 lightred=`echo -en "\033[91m"`
 lightgreen=`echo -en "\033[92m"`
 lightyellow=`echo -en "\033[93m"`
 lightblue=`echo -en "\033[94m"`
 lightpurple=`echo -en "\033[95m"`
 lightaqua=`echo -en "\033[96m"`
 white=`echo -en "\033[97m"`
 default=`echo -en "\033[39m"`
 BLACK=`echo -en "\033[40m"`
 RED=`echo -en "\033[41m"`
 GREEN=`echo -en "\033[42m"`
 ORANGE=`echo -en "\033[43m"`
 BLUE=`echo -en "\033[44m"`
 PURPLE=`echo -en "\033[45m"`
 AQUA=`echo -en "\033[46m"`
 GRAY=`echo -en "\033[47m"`
 DARKGRAY=`echo -en "\033[100m"`
 LIGHTRED=`echo -en "\033[101m"`
 LIGHTGREEN=`echo -en "\033[102m"`
 LIGHTYELLOW=`echo -en "\033[103m"`
 LIGHTBLUE=`echo -en "\033[104m"`
 LIGHTPURPLE=`echo -en "\033[105m"`
 LIGHTAQUA=`echo -en "\033[106m"`
 WHITE=`echo -en "\033[107m"`
 DEFAULT=`echo -en "\033[49m"`
